//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsMVCManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Voiture
    {
        public int Id { get; set; }
       [RegularExpression (@"\d{1,4} TU \d{1,3} | RS \d {1,6}",ErrorMessage ="Matricule nonvalide")]
         public string Matricule { get; set; }
        public EnumMarque Marque { get; set; }
        public string Couleur { get; set; }
        public EnumCarburant Carburant { get; set; }
        [DataType(DataType.Date)]
        public string DateMC { get; set; }
        public EnumModel Modele { get; set; }
        public int ProprietaireId { get; set; }
    
        public virtual Proprietaire Proprietaire { get; set; }
    }
}
