//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsMVCManager.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class ContactInfo
    {
        public string Adress { get; set; }
         [EmailAddress]  public string Email { get; set; }
        [RegularExpression (@"\d\d \d{3}\d{3}")] public string Tel { get; set; }
    }
}
